name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^3.0.0
  toastification: ^3.0.2
  gap: ^3.0.1
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  fpdart: ^1.1.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/examples/
    - assets/icons/
    - assets/examples/products/
    - assets/walk_through/


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon.png"
